[project]
name = "vollo-model-zoo"
version = "0.1.0"
description = "Exemplar models for the Vollo SDK "
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "beartype>=0.22.9",
  "torch>=2.10.0",
  "vollo-compiler>=26.1.0",
  "vollo-torch>=26.1.0",
]

[project.scripts]
zoo = "vollo_model_zoo.main:main"

[tool.uv]
package = true

[tool.pytest.ini_options]
addopts = "-v"

[dependency-groups]
dev = [
    "flash-linear-attention>=0.4.1",
    "matplotlib>=3.10.8",
    "pre-commit>=4.5.1",
    "pytest>=9.0.2",
]
